version: '3.7'
services:
  db:
    image: mysql
    ports:
        - 3306:3306
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment: 
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: cGFzc3dvcmQK

  wordpress:
    image: wordpress
    links:
      - db:mysql
    ports:
      - 80:80
    configs:
      - source: my_config
        target: /var/www/html
        uid: '33'
        gid: '33'
        mode: 0644
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      DB_NAME: wordpress
      DB_USER: root
      DB_PASSWORD: cGFzc3dvcmQK
      DB_HOST: db
      
  configs:
    my_config:
      file: ${PWD}/config/wp-config.php

  
 
      




